/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scientific.calculator;

/**
 *
 * @author gideonbamuleseyo
 */
public class ScientificCalc extends javax.swing.JFrame {
    public int calcHeight = 500;
    public int standardCalcWidth = 324;
    public int scientificCalcWidth = 600;
    public int jTextField1Width = scientificCalcWidth - 10;
    public int jTextField1Height = 40;
    
    double firstNum, secondNum, result;
    String operations;
    private Object math;

    /**
     * Creates new form ScientificCalc
     */
    public ScientificCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calcDisplay = new javax.swing.JTextField();
        jBtnSquareRoot = new javax.swing.JButton();
        jBtnBackSpace = new javax.swing.JButton();
        jBtnMultiply = new javax.swing.JButton();
        jBtnClear = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtnAdd = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtnSub = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtnDiv = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jBtnPoint = new javax.swing.JButton();
        jBtnMinusPlus = new javax.swing.JButton();
        jBtnEquals = new javax.swing.JButton();
        jBtnSinH = new javax.swing.JButton();
        jBtnLog = new javax.swing.JButton();
        jBtnSin = new javax.swing.JButton();
        jBtnPie = new javax.swing.JButton();
        jBtnCos = new javax.swing.JButton();
        jBtnCosH = new javax.swing.JButton();
        jBtnXPowerY = new javax.swing.JButton();
        jBtnTan = new javax.swing.JButton();
        jBtnTanH = new javax.swing.JButton();
        jBtnCbr = new javax.swing.JButton();
        jBtnRound = new javax.swing.JButton();
        jBtnSquare = new javax.swing.JButton();
        jBtnBinary = new javax.swing.JButton();
        jBtnCube = new javax.swing.JButton();
        jBtnHexaDecimal = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        calcDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        calcDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        calcDisplay.setText("0");
        calcDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcDisplayActionPerformed(evt);
            }
        });

        jBtnSquareRoot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnSquareRoot.setText("Sqrt");
        jBtnSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSquareRootActionPerformed(evt);
            }
        });

        jBtnBackSpace.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnBackSpace.setText("<= ");
        jBtnBackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackSpaceActionPerformed(evt);
            }
        });

        jBtnMultiply.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnMultiply.setText("X");
        jBtnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMultiplyActionPerformed(evt);
            }
        });

        jBtnClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnClear.setText("C");
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });

        jBtn7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });

        jBtn8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });

        jBtn9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });

        jBtnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnAdd.setText("+");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });

        jBtn4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });

        jBtnSub.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnSub.setText("-");
        jBtnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubActionPerformed(evt);
            }
        });

        jBtn5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });

        jBtn6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });

        jBtn3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });

        jBtnDiv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnDiv.setText("/");
        jBtnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivActionPerformed(evt);
            }
        });

        jBtn2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });

        jBtn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });

        jBtn0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });

        jBtnPoint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnPoint.setText(".");
        jBtnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPointActionPerformed(evt);
            }
        });

        jBtnMinusPlus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnMinusPlus.setText("+/-");
        jBtnMinusPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMinusPlusActionPerformed(evt);
            }
        });

        jBtnEquals.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnEquals.setText("=");
        jBtnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEqualsActionPerformed(evt);
            }
        });

        jBtnSinH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnSinH.setText("Sinh");
        jBtnSinH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSinHActionPerformed(evt);
            }
        });

        jBtnLog.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnLog.setText("Log");
        jBtnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLogActionPerformed(evt);
            }
        });

        jBtnSin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnSin.setText("Sin");
        jBtnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSinActionPerformed(evt);
            }
        });

        jBtnPie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnPie.setText("Pie");
        jBtnPie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPieActionPerformed(evt);
            }
        });

        jBtnCos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnCos.setText("Cos");
        jBtnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCosActionPerformed(evt);
            }
        });

        jBtnCosH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnCosH.setText("Cosh");
        jBtnCosH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCosHActionPerformed(evt);
            }
        });

        jBtnXPowerY.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnXPowerY.setText("x ^ y");
        jBtnXPowerY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnXPowerYActionPerformed(evt);
            }
        });

        jBtnTan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnTan.setText("Tan");
        jBtnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTanActionPerformed(evt);
            }
        });

        jBtnTanH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnTanH.setText("Tanh");
        jBtnTanH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTanHActionPerformed(evt);
            }
        });

        jBtnCbr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnCbr.setText("Cbr");
        jBtnCbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCbrActionPerformed(evt);
            }
        });

        jBtnRound.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnRound.setText("Rnd");
        jBtnRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRoundActionPerformed(evt);
            }
        });

        jBtnSquare.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnSquare.setText("x^2");
        jBtnSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSquareActionPerformed(evt);
            }
        });

        jBtnBinary.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnBinary.setText("Bin");
        jBtnBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBinaryActionPerformed(evt);
            }
        });

        jBtnCube.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnCube.setText("x ^ 3");
        jBtnCube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCubeActionPerformed(evt);
            }
        });

        jBtnHexaDecimal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnHexaDecimal.setText("Hex");
        jBtnHexaDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHexaDecimalActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnMinusPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtnBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtnSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnSinH, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnPie, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnCosH, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnXPowerY, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnTanH, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnCbr, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnRound, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnCube, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnHexaDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(calcDisplay))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(calcDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBtnSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtnBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBtnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnSinH, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBtnPie, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCosH, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBtnXPowerY, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnTanH, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBtnSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnCbr, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnRound, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnMinusPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBtnCube, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnHexaDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setResizable(true);
        this.setSize(scientificCalcWidth, calcHeight);
    }//GEN-LAST:event_formWindowActivated

    private void jBtnPieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPieActionPerformed
        double ops = 3.14159265;
        calcDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnPieActionPerformed

    private void jBtnHexaDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHexaDecimalActionPerformed
        int a = Integer.parseInt(calcDisplay.getText());
        calcDisplay.setText(Integer.toString(a, 16));
    }//GEN-LAST:event_jBtnHexaDecimalActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
        String num = calcDisplay.getText() + jBtn4.getText();
        calcDisplay.setText(num);
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        String num = calcDisplay.getText() + jBtn2.getText();
        calcDisplay.setText(num);
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
        String num = calcDisplay.getText() + jBtn7.getText();
        calcDisplay.setText(num);
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
        String num = calcDisplay.getText() + jBtn8.getText();
        calcDisplay.setText(num);
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        String num = calcDisplay.getText() + jBtn9.getText();
        calcDisplay.setText(num);
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
        String num = calcDisplay.getText() + jBtn5.getText();
        calcDisplay.setText(num);
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
        String num = calcDisplay.getText() + jBtn6.getText();
        calcDisplay.setText(num);
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
        String num = calcDisplay.getText() + jBtn1.getText();
        calcDisplay.setText(num);
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
        String num = calcDisplay.getText() + jBtn3.getText();
        calcDisplay.setText(num);
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
        String num = calcDisplay.getText() + jBtn0.getText();
        calcDisplay.setText(num);
    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        calcDisplay.setText("");
    }//GEN-LAST:event_jBtnClearActionPerformed

    private void jBtnBackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackSpaceActionPerformed
        String backSpace = null;
        if(calcDisplay.getText().length() > 0){
            StringBuilder strB = new StringBuilder(calcDisplay.getText());
            strB.deleteCharAt(calcDisplay.getText().length() - 1);
            backSpace = strB.toString();
            calcDisplay.setText(backSpace);
        }
    }//GEN-LAST:event_jBtnBackSpaceActionPerformed

    private void jBtnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPointActionPerformed
        if (!calcDisplay.getText().contains(".")){
            calcDisplay.setText(calcDisplay.getText() + jBtnPoint.getText());
        }
    }//GEN-LAST:event_jBtnPointActionPerformed

    private void jBtnMinusPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMinusPlusActionPerformed
        double ops = Double.parseDouble(String.valueOf(calcDisplay.getText()));
        ops = ops * (-1);
        calcDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnMinusPlusActionPerformed

    private void jBtnSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSquareActionPerformed
        double ops = Double.parseDouble(String.valueOf(calcDisplay.getText()));
        ops = (ops * ops);
        calcDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnSquareActionPerformed

    private void jBtnSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSquareRootActionPerformed
        double ops = Double.parseDouble(String.valueOf(calcDisplay.getText()));
        ops = Math.sqrt(ops);
        calcDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnSquareRootActionPerformed

    private void jBtnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLogActionPerformed
        double ops = Double.parseDouble(String.valueOf(calcDisplay.getText()));
        ops = Math.log(ops);
        calcDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnLogActionPerformed

    private void jBtnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSinActionPerformed
        double ops = Double.parseDouble(String.valueOf(calcDisplay.getText()));
        ops = Math.sin(ops);
        calcDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnSinActionPerformed

    private void jBtnSinHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSinHActionPerformed
        double ops = Double.parseDouble(String.valueOf(calcDisplay.getText()));
        ops = Math.sinh(ops);
        calcDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnSinHActionPerformed

    private void jBtnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCosActionPerformed
        double ops = Double.parseDouble(String.valueOf(calcDisplay.getText()));
        ops = Math.cos(ops);
        calcDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnCosActionPerformed

    private void jBtnCosHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCosHActionPerformed
        double ops = Double.parseDouble(String.valueOf(calcDisplay.getText()));
        ops = Math.cosh(ops);
        calcDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnCosHActionPerformed

    private void jBtnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTanActionPerformed
        double ops = Double.parseDouble(String.valueOf(calcDisplay.getText()));
        ops = Math.tan(ops);
        calcDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnTanActionPerformed

    private void jBtnTanHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTanHActionPerformed
        double ops = Double.parseDouble(String.valueOf(calcDisplay.getText()));
        ops = Math.tanh(ops);
        calcDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnTanHActionPerformed

    private void jBtnXPowerYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnXPowerYActionPerformed
        double ops = Double.parseDouble(String.valueOf(calcDisplay.getText()));
        ops = Math.pow(ops, ops);
        calcDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnXPowerYActionPerformed

    private void jBtnCubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCubeActionPerformed
        double ops = Double.parseDouble(String.valueOf(calcDisplay.getText()));
        ops = (ops * ops * ops);
        calcDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnCubeActionPerformed

    private void calcDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcDisplayActionPerformed

    private void jBtnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEqualsActionPerformed
        String answer;
        secondNum = Double.parseDouble(calcDisplay.getText());
        if(operations == "+"){
            result = firstNum + secondNum;
            answer = String.format("%.2f", result);
            calcDisplay.setText(answer);
        }else if(operations == "-"){
            result = firstNum - secondNum;
            answer = String.format("%.2f", result);
            calcDisplay.setText(answer);
        }else if(operations == "X"){
            result = firstNum * secondNum;
            answer = String.format("%.2f", result);
            calcDisplay.setText(answer);
        }else if(operations == "/"){
            result = firstNum / secondNum;
            answer = String.format("%.2f", result);
            calcDisplay.setText(answer);
        }
    }//GEN-LAST:event_jBtnEqualsActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        firstNum = Double.parseDouble(calcDisplay.getText());
        calcDisplay.setText(null);
        operations = "+";
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMultiplyActionPerformed
        firstNum = Double.parseDouble(calcDisplay.getText());
        calcDisplay.setText(null);
        operations = "X";
    }//GEN-LAST:event_jBtnMultiplyActionPerformed

    private void jBtnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubActionPerformed
        firstNum = Double.parseDouble(calcDisplay.getText());
        calcDisplay.setText(null);
        operations = "-";
    }//GEN-LAST:event_jBtnSubActionPerformed

    private void jBtnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivActionPerformed
        firstNum = Double.parseDouble(calcDisplay.getText());
        calcDisplay.setText(null);
        operations = "/";
    }//GEN-LAST:event_jBtnDivActionPerformed

    private void jBtnBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBinaryActionPerformed
        int a = Integer.parseInt(calcDisplay.getText());
        calcDisplay.setText(Integer.toString(a, 2));
    }//GEN-LAST:event_jBtnBinaryActionPerformed

    private void jBtnCbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCbrActionPerformed
        double ops = Double.parseDouble(String.valueOf(calcDisplay.getText()));
        ops = Math.cbrt(ops);
        calcDisplay.setText(String.valueOf(ops));                                       
    }//GEN-LAST:event_jBtnCbrActionPerformed

    private void jBtnRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRoundActionPerformed
        double ops = Double.parseDouble(String.valueOf(calcDisplay.getText()));
        ops = Math.round(ops);
        calcDisplay.setText(String.valueOf(ops));                                    
    }//GEN-LAST:event_jBtnRoundActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScientificCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField calcDisplay;
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnBackSpace;
    private javax.swing.JButton jBtnBinary;
    private javax.swing.JButton jBtnCbr;
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnCos;
    private javax.swing.JButton jBtnCosH;
    private javax.swing.JButton jBtnCube;
    private javax.swing.JButton jBtnDiv;
    private javax.swing.JButton jBtnEquals;
    private javax.swing.JButton jBtnHexaDecimal;
    private javax.swing.JButton jBtnLog;
    private javax.swing.JButton jBtnMinusPlus;
    private javax.swing.JButton jBtnMultiply;
    private javax.swing.JButton jBtnPie;
    private javax.swing.JButton jBtnPoint;
    private javax.swing.JButton jBtnRound;
    private javax.swing.JButton jBtnSin;
    private javax.swing.JButton jBtnSinH;
    private javax.swing.JButton jBtnSquare;
    private javax.swing.JButton jBtnSquareRoot;
    private javax.swing.JButton jBtnSub;
    private javax.swing.JButton jBtnTan;
    private javax.swing.JButton jBtnTanH;
    private javax.swing.JButton jBtnXPowerY;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
